name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Build Rust library
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-lib
        path: target/release/libpolycrypt_rs.so
        retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: ${{ github.workspace }}/target/release:$LD_LIBRARY_PATH
    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: rust-lib
        path: target/release

    - name: Copy artifacts to examples
      run: |
        cp target/release/libpolycrypt_rs.so examples/go/polycrypt/
        cp target/release/libpolycrypt_rs.so examples/python/polycrypt/

    - name: Run tests
      run: make test-all

    - name: Check test results
      run: |
        if [ $? -eq 0 ]; then
          echo "All tests passed successfully!"
          exit 0
        else
          echo "Some tests failed."
          exit 1
        fi
